AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for WatchExpense

Globals:
  Function:
    Timeout: 60

Resources:
  WatchExpensePublicBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: watch-expense-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  WatchExpensePublicBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WatchExpensePublicBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'WatchExpensePublicBucket'
                  - '/*'
  WatchExpenseLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: WatchExpenseS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Resource:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - Ref: 'WatchExpensePublicBucket'
                      - '/*'


Outputs:
  WatchExpensePublicBucketName:
    Description: Name of the public S3 bucket for WatchExpense
    Value: !Ref WatchExpensePublicBucket
