AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for WatchExpense

Globals:
  Function:
    Timeout: 60
    Runtime: provided.al2023
    Handler: bootstrap
    Architectures:
      - x86_64

Resources:
  WatchExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: watch-expense-table
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25

  WatchExpenseAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: WatchExpense_API
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  WatchExpenseLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WatchExpenseDynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Resource:
                  Fn::GetAtt:
                    - WatchExpenseTable
                    - Arn

  Health:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Health
      CodeUri: ./cmd/functions/health
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /health
            RestApiId: !Ref WatchExpenseAPI
  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Auth_Login
      CodeUri: ./cmd/functions/auth/login
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/auth/login
            RestApiId: !Ref WatchExpenseAPI
  AuthMe:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Auth_Me
      CodeUri: ./cmd/functions/auth/me
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/auth/me
            RestApiId: !Ref WatchExpenseAPI
  Logout:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Auth_Logout
      CodeUri: ./cmd/functions/auth/logout
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/auth/logout
            RestApiId: !Ref WatchExpenseAPI
  GetAllUsers:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_GetAllUsers
      CodeUri: ./cmd/functions/users/get-all-users
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/users
            RestApiId: !Ref WatchExpenseAPI
  GetUserById:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_GetUserById
      CodeUri: ./cmd/functions/users/get-user-by-id
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/users/{id}
            RestApiId: !Ref WatchExpenseAPI
  CreateUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_CreateUser
      CodeUri: ./cmd/functions/users/create-user
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/users
            RestApiId: !Ref WatchExpenseAPI
  UpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_UpdateUser
      CodeUri: ./cmd/functions/users/update-user
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /api/users/{id}
            RestApiId: !Ref WatchExpenseAPI
  DeleteUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_DeleteUser
      CodeUri: ./cmd/functions/users/delete-user
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /api/users/{id}
            RestApiId: !Ref WatchExpenseAPI
  GetUserBudget:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Users_GetUserBudget
      CodeUri: ./cmd/functions/users/get-user-budget
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/users/budget
            RestApiId: !Ref WatchExpenseAPI
  GetAllProjects:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Projects_GetAllProjects
      CodeUri: ./cmd/functions/projects/get-all-projects
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/admin/projects
            RestApiId: !Ref WatchExpenseAPI
  GetProjectById:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Projects_GetProjectById
      CodeUri: ./cmd/functions/projects/get-project-by-id
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/admin/projects/{id}
            RestApiId: !Ref WatchExpenseAPI
  CreateProject:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Projects_CreateProject
      CodeUri: ./cmd/functions/projects/create-project
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/admin/projects
            RestApiId: !Ref WatchExpenseAPI
  UpdateProject:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Projects_UpdateProject
      CodeUri: ./cmd/functions/projects/update-project
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /api/admin/projects/{id}
            RestApiId: !Ref WatchExpenseAPI
  GetAllDepartments:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Departments_GetAllDepartments
      CodeUri: ./cmd/functions/departments/get-all-departments
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/admin/departments
            RestApiId: !Ref WatchExpenseAPI
  GetDepartmentById:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Departments_GetDepartmentById
      CodeUri: ./cmd/functions/departments/get-department-by-id
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/admin/departments/{id}
            RestApiId: !Ref WatchExpenseAPI
  CreateDepartment:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Departments_CreateDepartment
      CodeUri: ./cmd/functions/departments/create-department
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/admin/departments
            RestApiId: !Ref WatchExpenseAPI
  UpdateDepartment:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Departments_UpdateDepartment
      CodeUri: ./cmd/functions/departments/update-department
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /api/admin/departments/{id}
            RestApiId: !Ref WatchExpenseAPI
  GetAllExpenses:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_GetAllExpenses
      CodeUri: ./cmd/functions/expenses/get-all-expenses
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/expenses
            RestApiId: !Ref WatchExpenseAPI
  GetExpenseById:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_GetExpenseById
      CodeUri: ./cmd/functions/expenses/get-expense-by-id
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/expenses/{id}
            RestApiId: !Ref WatchExpenseAPI
  CreateExpense:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_CreateExpense
      CodeUri: ./cmd/functions/expenses/create-expense
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/expenses
            RestApiId: !Ref WatchExpenseAPI
  UpdateExpense:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_UpdateExpense
      CodeUri: ./cmd/functions/expenses/update-expense
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /api/expenses/{id}
            RestApiId: !Ref WatchExpenseAPI
  UpdateExpenseStatus:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_UpdateExpenseStatus
      CodeUri: ./cmd/functions/expenses/update-expense-status
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /api/expenses/{id}
            RestApiId: !Ref WatchExpenseAPI
  GetExpenseSummary:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Expenses_GetExpenseSummary
      CodeUri: ./cmd/functions/expenses/get-expenses-summary
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/expenses/summary
            RestApiId: !Ref WatchExpenseAPI
  GetAllAdvances:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_GetAllAdvances
      CodeUri: ./cmd/functions/advances/get-all-advances
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/advance-request
            RestApiId: !Ref WatchExpenseAPI
  GetAdvanceById:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_GetAdvanceById
      CodeUri: ./cmd/functions/advances/get-advance-by-id
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/advance-request/{id}
            RestApiId: !Ref WatchExpenseAPI
  CreateAdvance:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_CreateAdvance
      CodeUri: ./cmd/functions/advances/create-advance
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/advance-request
            RestApiId: !Ref WatchExpenseAPI
  UpdateAdvance:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_UpdateAdvance
      CodeUri: ./cmd/functions/advances/update-advance
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /api/advance-request/{id}
            RestApiId: !Ref WatchExpenseAPI
  UpdateAdvanceStatus:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_UpdateAdvanceStatus
      CodeUri: ./cmd/functions/advances/update-advance-status
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /api/advance-request/{id}
            RestApiId: !Ref WatchExpenseAPI
  GetAdvanceSummary:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Advances_GetAdvanceSummary
      CodeUri: ./cmd/functions/advances/get-advances-summary
      Role: !GetAtt WatchExpenseLambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /api/advance-request/summary
            RestApiId: !Ref WatchExpenseAPI

  WatchExpensePublicBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: watch-expense-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  WatchExpensePublicBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WatchExpensePublicBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'WatchExpensePublicBucket'
                  - '/*'

  WatchExpenseImageUploadAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: WatchExpense_ImageUpload_API
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      BinaryMediaTypes:
        - "multipart/form-data"

  WatchExpenseS3LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WatchExpenseS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Resource:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - Ref: 'WatchExpensePublicBucket'
                      - '/*'

  UploadImage:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Images_UploadImage
      CodeUri: ./cmd/functions/images/upload
      Role: !GetAtt WatchExpenseS3LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /api/images
            RestApiId: !Ref WatchExpenseImageUploadAPI
  DeleteImage:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: WatchExpense_Images_DeleteImage
      CodeUri: ./cmd/functions/images/delete
      Role: !GetAtt WatchExpenseS3LambdaExecutionRole.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /api/images
            RestApiId: !Ref WatchExpenseImageUploadAPI

Outputs:
  WatchExpensePublicBucketName:
    Description: Name of the public S3 bucket for WatchExpense
    Value: !Ref WatchExpensePublicBucket
